### ISSUE TITLE
不知道的config.yaml

### ISSUE THREAD

**Issue by Alexicyer** [yxlllc/DDSP-SVC#113]
Traceback (most recent call last):
  File "gui_diff.py", line 544, in <module>
    gui = GUI()
  File "gui_diff.py", line 219, in __init__
    self.launcher()  # start
  File "gui_diff.py", line 296, in launcher
    self.event_handler()
  File "gui_diff.py", line 317, in event_handler
    self.start_vc()
  File "gui_diff.py", line 414, in start_vc
    self.svc_model.update_model(self.config.checkpoint_path, self.config.diff_project)
  File "gui_diff.py", line 54, in update_model
    self.ddsp_model, self.ddsp_args = load_model(ddsp_model_path, device=self.device)
  File "D:\fwwb\DDSP-SVC-master\ddsp\vocoder.py", line 479, in load_model
    with open(config_file, "r") as config:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/fwwb/DDSP-SVC-master/pretrain/rmvpe\\config.yaml'

**Comment by yxlllc** [comment]
加载错模型了
