### ISSUE TITLE
找不到exp/diffusion\\config.yaml

### ISSUE THREAD

**Issue by ChinoMofuMofu** [yxlllc/DDSP-SVC#114]
我是项目小白，完全没有接触过类似的工程，从第一步搭建环境开始就不知道对不对，具体来说我是这样做的：
首先安装anaconda，创建虚拟环境ddsp并下载pytorch，环境为torch 1.12.0 + torchaudio 0.12.0 + cuda 12.4，然后在release里下载ddsp5.0的文件并解压放在ddsp环境同文件夹中，通过Anaconda Prompt终端运行命令。
根据readme的指导配置了预训练模型，但我没有自己训练，而是将别人已经训练好的ddsp模型和扩散模型分别放在 exp/combsub-test 和 exp/diffusion-test 下，最后在终端运行非实时变声的命令python main_diff.py -i workplace/test.flac -ddsp exp/combsub-test/model_96000.pt -diff exp/diffusion/model_62000.pt -o workplace/output.wav -k 0 -speedup 0 -method pndm -kstep 100
然后出现报错：
Traceback (most recent call last):
  File "D:\Anaconda\envs\ddsp\DDSP-SVC-5.0\main_diff.py", line 206, in <module>
    model, vocoder, args = load_model_vocoder(cmd.diff_ckpt, device=device)
  File "D:\Anaconda\envs\ddsp\DDSP-SVC-5.0\diffusion\vocoder.py", line 28, in load_model_vocoder
    with open(config_file, "r") as config:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/diffusion\\config.yaml'
之前从来没有跑过类似的项目，对整体文件结构也不了解，所以这个报错我毫无头绪，希望能得到解答

**Comment by yxlllc** [comment]
缺少模型的配置文件，它应该是和模型的权重文件在一起的
