### ISSUE TITLE
你好楼楼，从B站下载的包只有"SVC-Fusion-v1.1.1.7z"这个文件夹，用7zip解压后，运行“启动web"弹窗内容如下

### ISSUE THREAD

**Issue by zmczmc123654** [yxlllc/DDSP-SVC#123]
Active code page: 65001
正在启动WebUI……
E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\
启动器工作目录:  E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\
License check passed.
2024-09-05 19:12:19.051557: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2024-09-05 19:12:20.283036: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\utils\import_utils.py", line 1472, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\generation\utils.py", line 93, in <module>
    from accelerate.hooks import AlignDevicesHook, add_hook_to_module
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\accelerate\accelerator.py", line 41, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\accelerate\tracking.py", line 43, in <module>
    from torch.utils import tensorboard
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import get_embedding_info, make_mat, make_sprite, make_tsv, write_pbtxt
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\lazy.py", line 50, in load_once
    module = load_fn()
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorboard\compat\__init__.py", line 45, in tf
    import tensorflow
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\__init__.py", line 47, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\distribute\distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\data\__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\data\experimental\__init__.py", line 98, in <module>
    from tensorflow.python.data.experimental import service
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\data\experimental\service\__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\data\experimental\ops\data_service_ops.py", line 26, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 34, in <module>
    from tensorflow.python.data.ops import iterator_ops
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 45, in <module>
    from tensorflow.python.training.saver import BaseSaverBuilder
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\training\saver.py", line 50, in <module>
    from tensorflow.python.training import py_checkpoint_reader
  File "C:\Users\11248\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\training\py_checkpoint_reader.py", line 19, in <module>
    from tensorflow.python.util._pywrap_checkpoint_reader import CheckpointReader
SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\utils\import_utils.py", line 1472, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\models\hubert\modeling_hubert.py", line 29, in <module>
    from ...modeling_utils import PreTrainedModel
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\modeling_utils.py", line 44, in <module>
    from .generation import GenerationConfig, GenerationMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\utils\import_utils.py", line 1462, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\utils\import_utils.py", line 1474, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
initialization of _pywrap_checkpoint_reader raised unreported exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\launcher.py", line 15, in <module>
    dist.launch_dialog()
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\dist.py", line 838, in launch_dialog
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\dist.py", line 821, in entry_point
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\dist.py", line 811, in main
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\dist.py", line 832, in TEST_UI
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\dist.py", line 36, in p5GZxeD1Km3X6fgjERBcsBQ1HrBqx1
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\package_utils\ui\ModelChooser.py", line 7, in <module>
    from package_utils.models.inited import model_name_list, model_list
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\package_utils\models\inited.py", line 6, in <module>
    from package_utils.models.ddsp import DDSPModel
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\package_utils\models\ddsp.py", line 24, in <module>
    from ddspsvc.reflow.vocoder import load_model_vocoder
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\ddspsvc\reflow\vocoder.py", line 11, in <module>
    from ddspsvc.ddsp.vocoder import CombSubSuperFast
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\ddspsvc\ddsp\vocoder.py", line 10, in <module>
    from transformers import HubertModel, Wav2Vec2FeatureExtractor
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\utils\import_utils.py", line 1463, in __getattr__
    value = getattr(module, name)
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\utils\import_utils.py", line 1462, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "E:\BaiduNetdiskDownload\SVC-Fusion\SVC-Fusion-v1.1.1\.conda\lib\site-packages\transformers\utils\import_utils.py", line 1474, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.hubert.modeling_hubert because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
initialization of _pywrap_checkpoint_reader raised unreported exception
Press any key to continue . . .

**Comment by yxlllc** [comment]
整合包相关问题请咨询发布方

**Comment by HuanLinOTO** [comment]
整合包加群问，麻烦close
