### ISSUE TITLE
推理时报错

### ISSUE THREAD

**Issue by fatinghenji** [yxlllc/DDSP-SVC#15]
使用的命令：`python main.py -i G:\DDSP-SVC\samples\source.wav -m G:\DDSP-SVC\exp\combsub-test\model_68000.pt -o G:\DDSP-SVC\test.wav --enhancer_adaptive_key 0 -id 1 -k 0 -e true -pe crepe`
日志：
```python
 [DDSP Model] Combtooth Subtractive Synthesiser
 [Loading] G:\DDSP-SVC\exp\combsub-test\model_68000.pt
Pitch extractor type: crepe
Extracting the pitch curve of the input audio...
Extracting the volume envelope of the input audio...
 [Encoder Model] Content Vec
 [Loading] pretrain/hubert/checkpoint_best_legacy_500.pt
2023-04-01 22:15:12 | INFO | fairseq.tasks.hubert_pretraining | current directory is G:\DDSP-SVC
2023-04-01 22:15:12 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-04-01 22:15:12 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Enhancer type: nsf-hifigan
| Load HifiGAN:  pretrain/nsf_hifigan/model
Traceback (most recent call last):
  File "main.py", line 197, in <module>
    enhancer = Enhancer(args.enhancer.type, args.enhancer.ckpt, device=device)
  File "G:\DDSP-SVC\enhancer.py", line 15, in __init__
    self.enhancer = NsfHifiGAN(enhancer_ckpt, device=self.device)
  File "G:\DDSP-SVC\enhancer.py", line 85, in __init__
    self.model, self.h = load_model(model_path, device=self.device)
  File "G:\DDSP-SVC\nsf_hifigan\models.py", line 17, in load_model
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pretrain/nsf_hifigan\\config.json'
```
错误日志中提到`pretrain/nsf_hifigan\\config.json`，但是我不清楚该文件应该如何生成或者下载。请问应该如何解决？

**Comment by fatinghenji** [comment]
问题解决，将下载的`nsf_hifigan_finetune`压缩包中的`config.json`放入对应的文件夹中。但是经过此操作后出现新的报错：
```python
PS G:\DDSP-SVC> python main.py -i G:\DDSP-SVC\samples\source.wav -m G:\DDSP-SVC\exp\combsub-test\model_68000.pt -o G:\DDSP-SVC\test.wav -id 1 -k 0 -e true
 [DDSP Model] Combtooth Subtractive Synthesiser
 [Loading] G:\DDSP-SVC\exp\combsub-test\model_68000.pt
Pitch extractor type: crepe
Extracting the pitch curve of the input audio...
Extracting the volume envelope of the input audio...
 [Encoder Model] Content Vec
 [Loading] pretrain/hubert/checkpoint_best_legacy_500.pt
2023-04-01 22:45:09 | INFO | fairseq.tasks.hubert_pretraining | current directory is G:\DDSP-SVC
2023-04-01 22:45:09 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-04-01 22:45:09 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Enhancer type: nsf-hifigan
| Load HifiGAN:  pretrain/nsf_hifigan/model
Traceback (most recent call last):
  File "main.py", line 197, in <module>
    enhancer = Enhancer(args.enhancer.type, args.enhancer.ckpt, device=device)
  File "G:\DDSP-SVC\enhancer.py", line 15, in __init__
    self.enhancer = NsfHifiGAN(enhancer_ckpt, device=self.device)
  File "G:\DDSP-SVC\enhancer.py", line 85, in __init__
    self.model, self.h = load_model(model_path, device=self.device)
  File "G:\DDSP-SVC\nsf_hifigan\models.py", line 25, in load_model
    cp_dict = torch.load(model_path, map_location=device)
  File "C:\Users\29099\.virtualenvs\DDSP-SVC-YOgpXN-h\lib\site-packages\torch\serialization.py", line 793, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\29099\.virtualenvs\DDSP-SVC-YOgpXN-h\lib\site-packages\torch\serialization.py", line 273, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\29099\.virtualenvs\DDSP-SVC-YOgpXN-h\lib\site-packages\torch\serialization.py", line 254, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'pretrain/nsf_hifigan/model'
```
请问`.\DDSP-SVC\pretrain`文件夹的正常文件目录应该是什么样子的啊，我已经糊涂了。

**Comment by fatinghenji** [comment]
进一步更新issue，这个文档我一言难尽（
解决上一楼的方案是：将下载的`nsf_hifigan_finetune`压缩包中的模型文件解压到`.\pretrain\nsf_hifigan\`文件夹中，并**重命名**为`model`。在进行上述操作后，遇到了新的问题：
```python
PS G:\DDSP-SVC> python main.py -i G:\DDSP-SVC\samples\source.wav -m G:\DDSP-SVC\exp\combsub-test\model_68000.pt -o G:\DDSP-SVC\test.wav -id 1 -k 0 -e true -eak 0
 [DDSP Model] Combtooth Subtractive Synthesiser
 [Loading] G:\DDSP-SVC\exp\combsub-test\model_68000.pt
Pitch extractor type: crepe
Extracting the pitch curve of the input audio...
Extracting the volume envelope of the input audio...
 [Encoder Model] Content Vec
 [Loading] pretrain/hubert/checkpoint_best_legacy_500.pt
2023-04-01 23:25:28 | INFO | fairseq.tasks.hubert_pretraining | current directory is G:\DDSP-SVC
2023-04-01 23:25:28 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
2023-04-01 23:25:28 | INFO | fairseq.models.hubert.hubert | HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Enhancer type: nsf-hifigan
| Load HifiGAN:  pretrain/nsf_hifigan/model
Traceback (most recent call last):
  File "main.py", line 197, in <module>
    enhancer = Enhancer(args.enhancer.type, args.enhancer.ckpt, device=device)
  File "G:\DDSP-SVC\enhancer.py", line 15, in __init__
    self.enhancer = NsfHifiGAN(enhancer_ckpt, device=self.device)
  File "G:\DDSP-SVC\enhancer.py", line 85, in __init__
    self.model, self.h = load_model(model_path, device=self.device)
  File "G:\DDSP-SVC\nsf_hifigan\models.py", line 26, in load_model
    generator.load_state_dict(cp_dict['generator'])
KeyError: 'generator'
```
这个问题彻底超出了我的解决能力，我咨询了bing，它给出的答复是：`这个错误通常是由于字典中不存在所需的键而引起的。在你的代码中，这个错误是由于缺少一个名为“generator”的键。你需要检查一下你的代码，看看是否有任何拼写错误或其他错误导致了这个问题。如果你需要更多帮助，请告诉我。`作为一个不会python的小白，我不会更改代码。

**Comment by fatinghenji** [comment]
我是笨比，你应该下载`nsf_hifigan`而不是`nsf_hifigan_finetune`

**Comment by mathpopo** [comment]
@fatinghenji nsf_hifigan在哪里下？
