### ISSUE TITLE
打开gui.py提示sounddevice.PortAudioError: Error opening Stream: Illegal combination of I/O devices [PaErrorCode -9993]

### ISSUE THREAD

**Issue by zx2021** [yxlllc/DDSP-SVC#46]
python 3.8
cuda11.8
torch2.0.0
torchaudio 2.0.1
windows10
所有的模型都配好了，报错如下，请问应如何解决
PS D:\AI\Audio\DDSP-SVC\DDSP-SVC> D:\AI\Audio\DDSP-SVC\Python38\python.exe gui.py --help
2023-05-06 07:16:43 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
event: stop_vc
event: start_vc
input device:1:阵列麦克风 (AMD Audio Device) (MME)
output device:7:扬声器 (Realtek(R) Audio) (Windows DirectSound)
crossfade_time:0.04
buffer_num:4
samplerate:44100
block_time:0.3
prefix_pad_length:1.13
mix_mode:None
enhancer:True
using_cuda:True
 [DDSP Model] Combtooth Subtractive Synthesiser
 [Loading] exp\multi_speaker\model_300000.pt
 [Encoder Model] HuBERT Soft
 [Loading] pretrain/hubert/hubert-soft-0d54a1f4.pt
| Load HifiGAN:  pretrain/nsf_hifigan/model
Removing weight norm...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\AI\Audio\DDSP-SVC\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\AI\Audio\DDSP-SVC\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 370, in soundinput
    with sd.Stream(callback=self.audio_callback, blocksize=self.block_frame, samplerate=self.config.samplerate,
  File "D:\AI\Audio\DDSP-SVC\Python38\lib\site-packages\sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "D:\AI\Audio\DDSP-SVC\Python38\lib\site-packages\sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "D:\AI\Audio\DDSP-SVC\Python38\lib\site-packages\sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening Stream: Illegal combination of I/O devices [PaErrorCode -9993]

**Comment by zx2021** [comment]
是单击“开始音频转换”之后才会报错

**Comment by yxlllc** [comment]
输入设备和输出设备是否正确设置了，两个需要一致

**Comment by LittleCutieeePIE** [comment]
解决了吗？
