### ISSUE TITLE
I can't get it to work.

### ISSUE THREAD

**Issue by NeMqki** [yxlllc/DDSP-SVC#66]
I tried to do it, but I get this.
Traceback (most recent call last):
  File "D:\DDSP-SVC\train.py", line 94, in <module>
    train(args, initial_global_step, model, optimizer, loss_func, loader_train, loader_valid)
  File "D:\DDSP-SVC\solver.py", line 83, in train
    for batch_idx, data in enumerate(loader_train):
  File "D:\DDSP-SVC\venv\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "D:\DDSP-SVC\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1348, in _next_data
    return self._process_data(data)
  File "D:\DDSP-SVC\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1374, in _process_data
    data.reraise()
  File "D:\DDSP-SVC\venv\lib\site-packages\torch\_utils.py", line 665, in reraise
    raise exception
RecursionError: Caught RecursionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\DDSP-SVC\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\DDSP-SVC\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\DDSP-SVC\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\DDSP-SVC\data_loaders.py", line 187, in __getitem__
    return self.__getitem__( (file_idx + 1) % len(self.paths))
  File "D:\DDSP-SVC\data_loaders.py", line 187, in __getitem__
    return self.__getitem__( (file_idx + 1) % len(self.paths))
  File "D:\DDSP-SVC\data_loaders.py", line 187, in __getitem__
    return self.__getitem__( (file_idx + 1) % len(self.paths))
  [Previous line repeated 1988 more times]
  File "D:\DDSP-SVC\data_loaders.py", line 186, in __getitem__
    if data_buffer['duration'] < (self.waveform_sec + 0.1):
RecursionError: maximum recursion depth exceeded in comparison

**Comment by yxlllc** [comment]
Check whether the training dataset and the validation dataset are placed correctly and the preprocessing is performed correctly.

**Comment by NeMqki** [comment]
https://zenn.dev/aivoicelab/articles/ddsp-svc-tutorial?redirected=1
I used this site for reference.
I did it exactly like this.
Are there any areas where I am wrong?

**Comment by yxlllc** [comment]
This error seems to be a problem related to importing data sets, and I can't see anything else. I still want to say, is your data set normal, and is the preprocessing performed correctly?
