### ISSUE TITLE
ModuleNotFoundError: jax requires jaxlib to be installed. Windows 11

### ISSUE THREAD

**Issue by koki-3615** [yxlllc/DDSP-SVC#67]
Hello. Recently, I've downgraded my CUDA to version 11.8(V11.8.89) and cuDNN to 8.6.0 for running another program. I'm not sure if this has caused the issue, but when I try to run DDSP, I encounter an error stating that 'jaxlib' is not installed, and thus I'm unable to use it.

Here are the commands I ran:

PS C:\Users\Pawn\DDSP-SVC> python main_diff.py -i input\audio.wav -ddsp exp\test\conbsub\model_90000.pt -diff exp\test\diff\model_15000.pt -o output\audio.wav -k 4 -id 1 -diffid 1 -speedup 1 -method dpm-solver -kstep 30
Traceback (most recent call last):
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\_src\lib\__init__.py", line 24, in <module>
    import jaxlib as jaxlib
ModuleNotFoundError: No module named 'jaxlib'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Pawn\DDSP-SVC\main_diff.py", line 12, in <module>
    from ddsp.vocoder import load_model, F0_Extractor, Volume_Extractor, Units_Encoder
  File "C:\Users\Pawn\DDSP-SVC\ddsp\vocoder.py", line 10, in <module>
    from transformers import HubertModel, Wav2Vec2FeatureExtractor
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\__init__.py", line 30, in <module>
    from .generic import (
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import jax.numpy as jnp
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\_src\config.py", line 24, in <module>
    from jax._src import lib
  File "C:\Users\Pawn\AppData\Local\Programs\Python\Python310\lib\site-packages\jax\_src\lib\__init__.py", line 26, in <module>
    raise ModuleNotFoundError(
ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.

-----------------------------------------------------------------------

and I have already tried these:
C:\Users\Pawn>pip install --upgrade "jax"
Requirement already satisfied: jax in c:\users\pawn\appdata\local\programs\python\python310\lib\site-packages (0.4.12)
Requirement already satisfied: ml-dtypes>=0.1.0 in c:\users\pawn\appdata\local\programs\python\python310\lib\site-packages (from jax) (0.2.0)
Requirement already satisfied: numpy>=1.21 in c:\users\pawn\appdata\local\programs\python\python310\lib\site-packages (from jax) (1.23.5)
Requirement already satisfied: opt-einsum in c:\users\pawn\appdata\local\programs\python\python310\lib\site-packages (from jax) (3.3.0)
Requirement already satisfied: scipy>=1.7 in c:\users\pawn\appdata\local\programs\python\python310\lib\site-packages (from jax) (1.9.3)

C:\Users\Pawn>pip install --upgrade "jaxlib"
ERROR: Could not find a version that satisfies the requirement jaxlib (from versions: none)
ERROR: No matching distribution found for jaxlib

------------------------------------------------------------

How can I resolve this issue?

**Comment by koki-3615** [comment]
Python 3.10.10

**Comment by koki-3615** [comment]
PS C:\Users\Pawn\DDSP-SVC> pip --version
pip 23.1.2 from C:\Users\Pawn\AppData\Roaming\Python\Python310\site-packages\pip (python 3.10)

**Comment by yxlllc** [comment]
Maybe pytorch should also be downgraded accordingly?

**Comment by koki-3615** [comment]
pip install "jax[cpu]===0.4.11" -f https://whls.blob.core.windows.net/unstable/index.html --use-deprecated legacy-resolver

Thank you for your response. The version of PyTorch also seems correct. I found a way to install a version of jaxlib that works on CPU, and DDSP is working again.
