### ISSUE TITLE
ImportError 内存资源不足，无法处理此命令

### ISSUE THREAD

**Issue by shoucandanghehe** [yxlllc/DDSP-SVC#85]
```
❯ python train_diff.py -c configs/diffusion-new.yaml
Traceback (most recent call last):
  File "train_diff.py", line 7, in <module>
    from diffusion.vocoder import Vocoder, Unit2Mel, Unit2Wav
  File "D:\AI\DDSP-SVC\diffusion\vocoder.py", line 11, in <module>
    from ddsp.vocoder import CombSubFast
  File "D:\AI\DDSP-SVC\ddsp\vocoder.py", line 7, in <module>
    import parselmouth
ImportError: DLL load failed while importing parselmouth: 内存资源不足，无法处理此命令。
```
但是我还有20G空闲内存？

**Comment by shoucandanghehe** [comment]
解决方法是先把parselmouth导进来（？
![image](https://github.com/yxlllc/DDSP-SVC/assets/51957264/cc33a7a3-f34b-453c-b2ba-278392372471)
![image](https://github.com/yxlllc/DDSP-SVC/assets/51957264/0343e85f-3c9a-4314-8117-b242b68aca4b)

**Comment by yxlllc** [comment]
你可以把diffusion-new.yaml里的cache_all_data选项设为False关闭缓存数据以节省内存，代价是训练速度可能会略微降低

**Comment by shoucandanghehe** [comment]
应该跟cache没关系，这还在import就爆了，而且只需要先把parselmouth导进来 之后的训练都可以正常进行
我更倾向于是这库或者py的内存管理有些神秘的bug？

**Comment by sky836** [comment]
我按照你的加入`import parselmouth`这行代码依旧没解决问题

**Comment by 2451265055** [comment]
I also encountered the same problem. When I was importing, I was prompted that I was out of memory, but I still had a lot of memory. Have you solved it?
