### ISSUE TITLE
gui_diff.py -> ValueError:  [x] Unknown Model: DiffusionNew

### ISSUE THREAD

**Issue by Sawaumi** [yxlllc/DDSP-SVC#86]
ran on python 3.8 (windows11) + cuda 11.8 + torch 2.0.0 + torchaudio 2.0.1
gui_diff.py would close itself on "start conversion", got it ran on pycharm and see what happened:

> Traceback (most recent call last):
  File "[...file name...]\DDSP-SVC-4.0\gui_diff.py", line 580, in <module>
    gui = GUI()
  File "[...file name...]\DDSP-SVC-4.0\gui_diff.py", line 229, in __init__
    self.launcher()  # start
  File "[...file name...]\DDSP-SVC-4.0\gui_diff.py", line 311, in launcher
    self.event_handler()
  File "[...file name...]\DDSP-SVC-4.0\gui_diff.py", line 335, in event_handler
    self.start_vc()
  File "[...file name...]\DDSP-SVC-4.0\gui_diff.py", line 447, in start_vc
    self.svc_model.update_model(self.config.checkpoint_path)
  File "[...file name...]\DDSP-SVC-4.0\gui_diff.py", line 52, in update_model
    self.model, self.args = load_model(model_path, device=self.device)
  File "[...file name...]\DDSP-SVC-4.0\ddsp\vocoder.py", line 486, in load_model
    raise ValueError(f" [x] Unknown Model: {args.model.type}")
ValueError:  [x] Unknown Model: DiffusionNew

model name "DiffusionNew" comes from this [https://github.com/yxlllc/DDSP-SVC/blob/master/train_diff.py](url) while certainly shouldnt be read from this
[https://github.com/yxlllc/DDSP-SVC/blob/master/ddsp/vocoder.py](url) 

Does this mean I loaded the wrong model?
model downloaded from [https://github.com/yxlllc/DDSP-SVC/releases/download/4.0/opencpop+kiritan.zip](url)
and had .../DDSP-SVC-4.0/exp/diffusion-new-demo/model_200000.pt loaded (i suppose thats done by chosing it) chosen.
Also the demo itself works fine (command lines) but gui does close itself.

**Comment by Sawaumi** [comment]
wait there wasnt a DiffusionNew type model was it? Is that model provided should I be loading that diffusion model?

Also: should i be training that another model seperately if I trained an 4.0 model by:
`python train_diff.py -c configs/diffusion-new.yaml`?

**Comment by Sawaumi** [comment]
update:
tried [https://github.com/CNChTu/Diffusion-SVC](url) and the sample combined model
gui still kills itself by the time i start conversion

**Comment by yxlllc** [comment]
You need to load the diffusion model in the right hand side of the gui.  The DDSP model in the left hand side can be empty if this is a 4.0 model.

**Comment by thedoctorbeat** [comment]
Hello! Mine also crashes when process starts.  
Is there somewhere where I can find a step by step on how to use, train and all that???
All things I see are in Chinese, ahahah... Even the gui

I have ValueError:  [x] Unknown Model: Diffusion

**Comment by KillauraHacks** [comment]
It seems Diffusion and DiffusionNew are not implemented and are missing from the vocoder.py
