### ISSUE TITLE
訓練階段遇到的問題

### ISSUE THREAD

**Issue by guitarj** [yxlllc/DDSP-SVC#88]
Traceback (most recent call last):
  File "train_diff.py", line 86, in <module>
    train(args, initial_global_step, model, optimizer, scheduler, vocoder, loader_train, loader_valid)
  File "/home/csmxj/DDSP-SVC/diffusion/solver_new.py", line 188, in train
    test_ddsp_loss, test_diff_loss = test(args, model, vocoder, loader_test, saver)
  File "/home/csmxj/DDSP-SVC/diffusion/solver_new.py", line 25, in test
    for bidx, data in enumerate(loader_test):
  File "/root/.miniconda/envs/ddsp/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/root/.miniconda/envs/ddsp/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/.miniconda/envs/ddsp/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.miniconda/envs/ddsp/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/csmxj/DDSP-SVC/diffusion/data_loaders.py", line 203, in __getitem__
    return self.__getitem__( (file_idx + 1) % len(self.paths))
  File "/home/csmxj/DDSP-SVC/diffusion/data_loaders.py", line 203, in __getitem__
    return self.__getitem__( (file_idx + 1) % len(self.paths))
  File "/home/csmxj/DDSP-SVC/diffusion/data_loaders.py", line 203, in __getitem__
    return self.__getitem__( (file_idx + 1) % len(self.paths))
  [Previous line repeated 989 more times]
  File "/home/csmxj/DDSP-SVC/diffusion/data_loaders.py", line 202, in __getitem__
    if data_buffer['duration'] < (self.waveform_sec + 0.1):
RecursionError: maximum recursion depth exceeded in comparison

在訓練完一個區間後會做一次validation,就在這邊陷入RecursionError了。

**Comment by yxlllc** [comment]
数据集里音频切片的长度不能小于 2s （配置文件里有相关参数）
